export type Language = "en" | "zh";

export const content = {
  en: {
    name: "Xuejia Shi",
    role: "Senior Full-Stack Engineer",
    intro: "I design and build reliable production platforms, full-stack applications, and practical AI agent products.",
    location: "Shanghai, China",
    nav: ["About", "Journey", "Projects", "Contact"],
    aboutTitle: "About",
    about: [
      "Hi, I’m Xuejia, a full-stack engineer based in Shanghai. I studied Software Engineering and Economics at Xiamen University, which shaped how I look at both the engineering problem and the user or business need behind it.",
      "I joined Citi in 2017 and progressed from Software Engineer to AVP / Full-Stack Tech Lead. My work has grown from hands-on React engineering on Citi Velocity to end-to-end ownership of Java / Spring services, React applications, REST APIs, MongoDB models, and production delivery for CitiDirect Nextgen Entitlements.",
      "Today I remain hands-on with architecture, code reviews, and core implementation—most recently the core User Service and schema-driven React permission workflows for CitiDirect Nextgen Entitlements. Alongside that work, I lead technical delivery across a 10+ person China–India team, directly manage six engineers, and collaborate with Product, UX, Operations, CRM, and five global engineering teams.",
      "More recently, I independently built Baby Food Buddy from idea to a live product used by 300+ people. It combines a WeChat Mini Program, React operations console, TypeScript / Node.js APIs, a production single-agent DeepSeek workflow, and standards-based MCP tooling.",
      "I’m looking for full-stack infrastructure work where scalability, production reliability, thoughtful user experience, and practical AI tool use all matter.",
    ],
    projectsTitle: "Selected projects",
    projectsHint: "Project details are currently unavailable.",
    openProject: "Project details unavailable",
    closeProject: "Close project",
    backToPortfolio: "Back to portfolio",
    previousProject: "Previous project",
    nextProject: "Next project",
    projectPageLabel: "Project story",
    detailLabels: { challenge: "Context & challenge", ownership: "My ownership", approach: "How I approached it", impact: "Outcome" },
    featured: "Featured project",
    projects: [
      {
        id: "fushi",
        title: "Baby Food Buddy",
        role: "Independent Full-Stack / AI Engineer · 300+ users · Active development",
        body: "A live full-stack product for families with babies aged 4–24 months. It combines a CloudBase-hosted single-agent DeepSeek workflow with deterministic TypeScript tools, plus a standards-based MCP server built over shared profile, menu, inventory and reaction capabilities.",
        result: "Reached 300+ cumulative users by August 2026 while sustaining over 96% API and approximately 90% React line coverage across the evolving production codebase.",
        outcomeStatement: "From independent build to real-world use",
        outcomes: [["300+", "cumulative users by Aug 2026"], ["Live", "AI-assisted planning and food tracking in production"], [">96% / ~90%", "API / React line coverage"]],
        detail: {
          challenge: "Families introducing solid foods to babies aged 4–24 months repeatedly face three practical questions: what should the baby eat today, which foods have already been tried, and what may have caused a reaction. Baby Food Buddy brings meal planning, introduction history, reaction tracking and AI-assisted guidance into one product, while keeping AI actions inside explicit safety rules.",
          ownership: "As the sole builder, I own product and interaction design, implementation, testing, CloudBase deployment, and production debugging across the WeChat Mini Program, React operations console, TypeScript / Node.js APIs, production DeepSeek agent, and MCP server.",
          approach: ["Built a controlled single-agent workflow — integrated DeepSeek with deterministic TypeScript tools while enforcing authorization, food-safety rules, state-change confirmation and execution limits at the application layer.", "Built a standards-based MCP server — exposed shared profile, menu, inventory and reaction capabilities as 23 Tools, 10 read-only Resources and 3 Prompts using the official TypeScript SDK; Zod validates protocol boundaries, and read-only Resources remain separate from state-changing Tools.", "Designed a type-safe full-stack architecture — centralized oRPC and Zod request, response and validation schemas in a pnpm monorepo; React Router manages routing, while TanStack Query and Zustand separate server state from local workflow state.", "Built a secure React operations console — designed role-based triage, investigation, escalation, resolution and closure flows with token authentication, server-side authorization, optimistic concurrency and auditable state transitions, while preventing edits to family allergy records.", "Built reproducible quality gates — automated Agent Runtime regressions plus API, React / MSW, Playwright E2E and MCP tests; added summary-only tool traces and nine fixed offline cases as a deterministic regression baseline, not a production-model accuracy metric.", "Accelerated delivery with AI-assisted engineering — used Claude Code and Codex to complete a working WeChat Mini Program POC in one day and accelerate later implementation and test-case generation."],
        },
        tags: ["DeepSeek / LLM Agent Runtime", "MCP Client / Server", "MCP Tools / Resources / Prompts", "TypeScript / React 19", "Node.js / Express", "oRPC / Zod", "Vitest / MSW / Playwright", "CloudBase / pnpm / Vite"],
        link: "View source",
      },
      {
        id: "nextgen",
        title: "CitiDirect Nextgen Entitlements",
        role: "Tech Lead / Senior Software Engineer · 2023.01—Present",
        body: "Co-designed and delivered CitiDirect Nextgen Entitlements’s shared identity and access-control foundation, covering client onboarding, the full user lifecycle, dynamic permission assignment, and maker-checker approvals across Spring services and React applications.",
        result: "Released the complete Entitlements administration lifecycle to production, cleared 100+ security findings across team services, maintained 90%+ automated coverage, and supported secure biweekly releases. Recognised individually with the 2024 Citi Gratitude Golden Award.",
        outcomeStatement: "Put the complete user-administration journey into production",
        outcomes: [["100+", "security findings cleared across team services"], ["Live", "complete user and entitlement administration lifecycle"], ["Biweekly", "Kubernetes / OpenShift production releases"], ["2024", "Citi Gratitude Golden Award · individual recognition"]],
        detail: {
          casePages: ["Leadership & architecture", "Production engineering"],
          challenge: "CitiDirect serves 90K+ organizations across 90+ markets. Entitlements is its shared identity and access-control foundation for client onboarding, ongoing client management, full user-lifecycle management, permission assignment, and dual-control approvals.",
          focus: "Co-designed the domain and full-stack architecture, then led production delivery.",
          scope: "As Tech Lead, I manage six engineers in China, lead the broader 10+ person China–India team, and coordinate integration with five other engineering teams and CRM partners.",
          architectureTitle: "A shared full-stack user and entitlement foundation",
          architectureSummary: "The platform connects user-lifecycle workflows, metadata-driven permissions, consistent data changes, and default-deny API authorization across independently deployed services and applications.",
          architectureColumns: ["Operational concern", "NextGen approach"],
          architectureRows: [["User lifecycle", "Fragmented administration", "Maker create / modify / delete; checker approve / reject"], ["Permission experience", "Static forms", "Backend metadata and schema-driven workflow"], ["Data consistency", "Separate user and access updates", "Indexed collections with atomic MongoDB transactions"], ["API authorization", "Repeated service-specific logic", "OAuth 2.0 / JWT and a shared default-deny security library"]],
          onboardingFlow: ["CRM onboarding event", "Create Legal Entity", "Trigger downstream provisioning", "Validate user and entitlement state"],
          contributionTitle: "Contributions across architecture, delivery and production engineering",
          contributions: [["Designed backend services and resilient integrations", "Defined service boundaries and OpenAPI contracts within a platform of 40+ Spring services, and implemented the core User Service with WebFlux / WebClient, validation, idempotency, error propagation and explicit timeouts."], ["Built the dynamic React workflow and UI platform", "Implemented metadata and schema-driven permission assignment with lazy-loaded panels, and built a Module Federation framework for five React applications deployed on Nginx."], ["Designed consistent data and onboarding flows", "Modelled indexed MongoDB user and entitlement collections with atomic lifecycle updates, and connected CRM events to downstream Legal Entity, user and entitlement provisioning."], ["Engineered authorization and production controls", "Co-designed OAuth 2.0 / JWT authorization, a shared default-deny Spring Security library, automated quality gates, structured diagnostics, Actuator health checks, and Kibana-based incident investigation."]],
          scaleMetrics: [["Live", "complete administration lifecycle in production"], ["100+", "security findings cleared across team services"], ["90%+", "automated test coverage"], ["Golden", "Citi Gratitude Award · 2024"]],
          deliveryTitle: "Engineered the controls required for production",
          deliverySummary: "Beyond feature delivery, I co-designed the authorization layer and embedded security, testing, monitoring and rollback controls into the delivery path.",
          migrationSteps: ["Review legacy setup", "Group clients", "Map to Personas", "Set migration rules", "Validate and roll out"],
          securityTracks: [["Authorization Server", "Co-designed and implemented as a separate authorization platform capability."], ["Shared Spring Security JAR", "Enforces YAML-configured API permissions, JWT roles and actions, and a default-deny policy inside application services."]],
          securityTools: "SonarQube · Snyk · SAST · BDD / Cucumber · GitLab CI / Harness",
          deliveryPillars: [["Standardized API authorization", "Co-designed an OAuth 2.0 Authorization Server for short-lived JWTs and refresh-token renewal, and built a shared Spring Security JAR that enforces YAML-defined, default-deny rules."], ["Embedded security and quality gates", "Integrated SonarQube, Snyk, SAST and automated tests into GitLab CI / Harness, making remediation a release condition."], ["Made production behavior diagnosable", "Added structured logs, request IDs and Actuator health checks, and used Kibana to trace cross-service failures in Kubernetes / OpenShift production."]],
          ownership: "As Tech Lead / Senior Software Engineer for Entitlements, I co-designed the domain model and Spring architecture, led production delivery of the end-to-end user-administration journey, and coordinated five other engineering teams and CRM partners. I manage six engineers in China and lead the broader 10+ person China–India team.",
          approach: ["Built the full administration lifecycle — implemented maker create, modify and delete requests, checker approval and rejection, and synchronized entitlement changes.", "Delivered automated Legal Entity onboarding — connected CRM events to downstream user and entitlement provisioning through an event-driven workflow.", "Co-designed a phased legacy-model transition — analysed production data and defined transformation rules for tens of millions of Access Profiles while the legacy and new models continue to coexist.", "Standardized authorization and production diagnostics — combined shared default-deny security controls with automated gates, request-level tracing, Actuator health checks and Kibana incident investigation."],
        },
        tags: ["Java / Spring Boot / Spring Cloud", "React Micro-frontends", "OAuth 2.0 / Spring Security / JWT", "Event-driven Microservices", "GitLab CI / Harness", "Kubernetes / OpenShift"],
      },
      {
        id: "velocity",
        title: "Citi Velocity Content & Search",
        role: "Software Engineer / Technical Lead · 2017.07—2022.12",
        body: "Led frontend modernization across Content, Notification and Search on Citi Velocity, a platform serving nearly 100,000 institutional investors across 150 countries and integrating more than 200 business applications.",
        result: "Reduced initial wait and blank-screen time by about 60%, delivered the complete Search experience, received the 2019 Golden and 2021 Silver Awards, and presented the architecture and performance work at a company-wide engineering conference.",
        outcomeStatement: "Delivered the complete search experience",
        outcomes: [["≈60%", "reduction in initial wait and blank-screen time"], ["End-to-end", "Search-box typeahead and the complete results page"], ["Golden + Silver", "Citi Gratitude Awards · 2019 / 2021 · company-wide engineering conference speaker"]],
        detail: {
          challenge: "Citi Velocity serves nearly 100,000 institutional investors across 150 countries and integrates 200+ applications. Its second-highest-traffic entry point had to unify research, market data, multimedia and applications, integrate market-data portlets maintained by different teams, and replace a slow legacy frontend.",
          focus: "Led frontend modernization across Content, Notification and Search",
          scope: "As a hands-on Technical Lead, I led four frontend engineers across Content, Notification and Search, owned the Search UI architecture and performance strategy, and coordinated API and release dependencies with four data teams.",
          architectureTitle: "Built metadata-driven React rendering",
          architectureSummary: "Metadata-driven rendering unified heterogeneous result types; a shared FDC3 contract passed search parameters consistently to market-data portlets maintained by different teams.",
          architectureNodes: [["Mapped content to reusable components", "React · TypeScript · Strategy Pattern · extensible result types"], ["Standardized portlet integration through FDC3", "shared contract · consistent search parameters · independently maintained portlets"]],
          actionMeta: ["React · TypeScript · Strategy Pattern", "FDC3 · Cross-app APIs · Events", "WebSocket · Real-time Notifications", "Webpack · Code Splitting · CI/CD · Canary Release"],
          ownership: "As a hands-on Technical Lead, I led four frontend engineers responsible for Content, Notification and Search. I owned the Search UI architecture and performance strategy, delivered the complete experience from typeahead through the results page, and coordinated API and release dependencies with four data teams.",
          approach: ["Built configurable Search rendering — used React, TypeScript and the Strategy Pattern to map research, market data and multimedia into reusable components, allowing new result types to be introduced through configuration.", "Standardized Search portlet integration — defined a shared FDC3 contract for passing search parameters to market-data portlets maintained by different teams, giving every portlet one consistent integration pattern.", "Delivered WebSocket-based notifications — led the Notification module integration to provide real-time user updates without repeated polling.", "Improved performance and release safety — combined Webpack code splitting, lazy loading and Skeleton Screens with reusable CI/CD templates and canary releases for a high-traffic entry point."],
        },
        tags: ["React / TypeScript", "Metadata-driven UI", "FDC3 APIs / Events", "WebSocket / Real-time Notifications", "Webpack / Code Splitting", "CI/CD Templates / Canary Release"],
      },
      {
        id: "platform",
        title: "Enterprise React Component Library",
        role: "Core Developer · 2018.07—2019.01",
        body: "Helped build a React / TypeScript component library from the ground up so three business lines could reuse the same implementation while preserving their own interface styles.",
        result: "The library supported four interface standards and eight themes, was adopted by three core business lines, and reduced duplicate UI work through consistent component APIs and adoption guidance.",
        outcomeStatement: "Turned duplicated UI work into a shared component library",
        outcomes: [["3", "core business lines adopted the library"], ["8 themes", "across four interface standards"]],
        detail: {
          challenge: "Three business lines maintained their own UI components and themes, so similar features were repeatedly rebuilt even though each product still needed to preserve its own visual identity.",
          focus: "Helped build a shared React component library from the ground up",
          scope: "As a core developer, I worked on component APIs, theme extensibility and adoption documentation.",
          ownership: "As a core developer during the library’s initial build, I helped shape its React / TypeScript implementation and extension model, covering component APIs, themes and adoption documentation.",
          approach: ["Built reusable React component APIs — defined shared behaviour and stable TypeScript interfaces so teams could reuse components without coupling them to one business line.", "Supported multiple design systems through themes — separated core component logic from SCSS themes and configuration, supporting four interface standards and eight visual themes on one implementation.", "Documented component adoption — provided API references and developer guides so teams could configure and adopt components without rebuilding the same solutions."],
          actionMeta: ["React · TypeScript · Component APIs", "SCSS · Theme Configuration · Design Systems", "API Documentation · Developer Guides"],
        },
        tags: ["React / TypeScript", "Shared Component Library", "Component APIs", "SCSS / Theming", "Multi-theme Design System", "Developer Documentation"],
      },
    ],
    galleryTabs: ["Product overview", "Why it matters", "Home experience", "Support console"],
    galleryCaptions: [
      "Baby Food Buddy brings meal planning, food-introduction tracking, reaction history and pantry management into one mini-program.",
      "The product grew from the small but demanding questions parents face every day: what to cook, what has been tried, what may have caused a reaction and what is still in the fridge.",
      "The home screen turns today’s meals, progress, reaction logging, suggestions and tomorrow’s plan into one practical checklist.",
      "With user consent, the support console exposes only the diagnostics needed to investigate and escalate issues—without allowing staff to edit family allergy data.",
    ],
    galleryAlt: ["Baby Food Buddy product overview poster showing the mini-program and its core features", "Illustrated poster explaining four everyday complementary-feeding challenges for parents", "Baby Food Buddy home-screen guide showing daily meal and reaction-tracking features", "Baby Food Buddy web support console showing the case queue and selected case details"],
    journeyTitle: "Engineering journey",
    journeyIntro: "My core experience comes from building and leading enterprise systems at Citi; more recently, I have extended that foundation by taking an AI agent product from idea to real-world use.",
    journey: [
      { period: "2017—Present", title: "Citi · AVP / Senior Software Engineer", body: "Grew from an individual contributor into a Tech Lead and people manager, while staying hands-on with the systems my teams deliver.", stages: [
        ["Today", "Building and leading across the stack", "Develop core backend and frontend features, guide a China–India team, and work with global partners to move a complex banking platform forward safely."],
        ["Earlier years", "Making front ends faster and easier to build", "Rebuilt a high-traffic search experience and helped create reusable React components for several business lines."],
      ] },
      { period: "2026—Now", title: "Extending my full-stack work into AI agents", body: "Designed and launched Baby Food Buddy, combining a production single-agent DeepSeek workflow with deterministic guardrails and standards-based MCP tooling.", stages: [] },
      { period: "2013—2017", title: "Xiamen University", body: "Studied Software Engineering and Economics, learning to look at products from both a technical and business perspective.", stages: [] },
    ],
    contactTitle: "Let’s build something dependable.",
    contactBody: "I’m interested in full-stack engineering roles where product judgment, implementation quality and long-term ownership all matter.",
    email: "Email me",
    source: "GitHub profile",
    archive: "Writing archive · 2016—2018",
    footer: "Designed and built by Xuejia Shi",
  },
  zh: {
    name: "史学佳",
    role: "高级全栈工程师",
    intro: "我设计并构建可靠的生产平台、全栈应用，以及真正投入使用的 AI Agent 产品。",
    location: "中国上海",
    nav: ["关于", "成长路径", "项目", "联系"],
    aboutTitle: "关于我",
    about: [
      "你好，我是史学佳，一名在上海工作的全栈工程师。我本科毕业于厦门大学，拥有软件工程和经济学双学位，这让我习惯同时理解工程问题，以及背后的用户和业务需求。",
      "2017 年加入花旗后，我从软件工程师成长为 AVP / Full-Stack Tech Lead。工作范围也从 Citi Velocity 的 React 一线开发，扩展到 CitiDirect Nextgen Entitlements 的 Java / Spring 服务、React 应用、REST API、MongoDB 数据模型和生产交付。",
      "目前，我仍然直接参与架构、代码评审和核心功能实现，最近的重点包括 CitiDirect Nextgen Entitlements 核心 User Service 和 Schema 驱动的 React 权限流程。在一线开发之外，我负责 10 余人中印团队的技术交付，直接管理 6 名工程师，并与 Product、UX、Operations、CRM 及另外 5 个全球研发团队协作。",
      "最近，我把实际育儿需求做成了“辅食搭子（Baby Food Buddy）”，并独立完成从想法到上线的全过程。产品目前有 300+ 用户，由微信小程序、React 运营后台、TypeScript / Node.js API、线上单 Agent DeepSeek 工作流和符合标准的 MCP 工具能力组成。",
      "我希望继续从事同时重视扩展性、生产可靠性、用户体验和实际 AI 工具应用的全栈基础设施工作。",
    ],
    projectsTitle: "精选项目",
    projectsHint: "项目详情暂未开放。",
    openProject: "项目详情暂未开放",
    closeProject: "关闭项目",
    backToPortfolio: "返回作品集",
    previousProject: "上一个项目",
    nextProject: "下一个项目",
    projectPageLabel: "项目详解",
    detailLabels: { challenge: "背景与挑战", ownership: "我的职责", approach: "解决方式", impact: "项目结果" },
    featured: "重点项目",
    projects: [
      {
        id: "fushi",
        title: "辅食搭子",
        role: "独立全栈 / AI 工程师 · 300+ 用户 · 持续迭代中",
        body: "一款面向 4–24 月龄宝宝家庭的线上全栈产品。运行于 CloudBase 的单 Agent DeepSeek 工作流与确定性 TypeScript Tools 协同执行操作，同时通过符合标准的 MCP Server 开放共享的档案、菜单、库存与反应记录能力。",
        result: "截至 2026 年 8 月累计用户超过 300 人；在生产代码持续迭代的同时，API 行覆盖率保持在 96% 以上，React 行覆盖率约 90%。",
        outcomeStatement: "从独立开发走到真实用户使用",
        outcomes: [["300+", "截至 2026 年 8 月累计用户"], ["已上线", "AI 辅食规划与食物记录投入真实使用"], [">96% / ~90%", "API / React 行覆盖率"]],
        detail: {
          challenge: "4–24 月龄宝宝家庭每天都要反复确认：今天吃什么、哪些食材已经尝试过、宝宝不舒服可能和什么有关。“辅食搭子”把辅食规划、食材引入记录、不适回溯和 AI 辅助建议放进同一款产品，并让 AI 操作始终处于明确的安全规则内。",
          ownership: "作为唯一开发者，我负责产品与交互设计、实现、测试、CloudBase 部署和线上排障，覆盖微信小程序、React 运营后台、TypeScript / Node.js API、线上 DeepSeek Agent 与 MCP Server。",
          approach: ["构建受控的单 Agent 工作流——将 DeepSeek 与确定性的 TypeScript Tools 集成，并由应用层执行授权、食物安全规则、状态变更确认及执行上限控制。", "构建符合标准的 MCP Server——使用官方 TypeScript SDK，将共享能力开放为 23 个 Tools、10 个只读 Resources 和 3 个 Prompts；通过 Zod 校验协议边界，并将只读 Resources 与会改变状态的 Tools 分离。", "设计类型安全的全栈架构——在 pnpm Monorepo 中集中定义 oRPC 与 Zod 请求、响应及校验 Schema；使用 React Router 管理路由，并通过 TanStack Query / Zustand 分离服务端状态与本地流程状态。", "构建安全的 React 运营控制台——设计覆盖分流、调查、升级、解决与关闭的角色化流程，通过 Token 认证、服务端授权、乐观并发控制和可审计状态流转保护操作边界，并禁止修改家庭过敏档案。", "构建可重复的质量门禁——自动化 Agent Runtime 回归以及 API、React / MSW、Playwright E2E 和 MCP 测试；通过摘要式 Tool Trace 与 9 个固定离线案例建立确定性回归基线，而非线上模型准确率指标。", "通过 AI 辅助研发加速交付——使用 Claude Code 与 Codex 在一天内完成可运行的微信小程序 POC，并加速后续功能实现和测试用例生成。"],
        },
        tags: ["DeepSeek / LLM Agent Runtime", "MCP Client / Server", "MCP Tools / Resources / Prompts", "TypeScript / React 19", "Node.js / Express", "oRPC / Zod", "Vitest / MSW / Playwright", "CloudBase / pnpm / Vite"],
        link: "查看源码",
      },
      {
        id: "nextgen",
        title: "CitiDirect Nextgen Entitlements",
        role: "Tech Lead / Senior Software Engineer · 2023.01—至今",
        body: "共同设计并交付 CitiDirect Nextgen Entitlements 的统一身份与访问控制基础能力，覆盖客户开户、完整用户生命周期、动态权限分配和 Maker-Checker 审批，横跨 Spring 服务与 React 应用。",
        result: "完整 Entitlements 管理生命周期已投入生产；清理团队服务中的 100+ 个安全问题，保持 90%+ 自动化测试覆盖，并支持安全的双周发布。个人获得 2024 年 Citi Gratitude Golden Award。",
        outcomeStatement: "将完整用户管理链路投入生产",
        outcomes: [["100+", "清理团队服务中的安全问题"], ["已上线", "完整用户与权限管理生命周期"], ["双周", "Kubernetes / OpenShift 生产发布"], ["2024", "Citi Gratitude Golden Award · 个人获奖"]],
        detail: {
          casePages: ["领导力与架构", "生产工程"],
          challenge: "CitiDirect 服务 90+ 个市场的 90K+ 家机构。Entitlements 是其统一身份与访问控制基础能力，负责客户开户、持续的客户管理、完整用户生命周期、权限分配和双人复核审批。",
          focus: "共同设计领域模型与全栈架构，并带领团队完成生产交付。",
          scope: "作为 Tech Lead，我直接管理 6 名中国工程师，带领更广泛的 10 余人中印团队，并协调另外 5 个研发团队和 CRM 合作方完成集成。",
          architectureTitle: "统一的全栈用户与权限基础能力",
          architectureSummary: "平台把用户生命周期、元数据驱动权限、数据一致性和默认拒绝的 API 授权连接起来，并支持各服务和应用独立部署。",
          architectureColumns: ["运营问题", "NextGen 方案"],
          architectureRows: [["用户生命周期", "管理流程分散", "Maker 创建／修改／删除，Checker 审批／拒绝"], ["权限体验", "静态表单", "后端 Metadata 与 Schema 驱动"], ["数据一致性", "用户与权限分别更新", "索引集合与 MongoDB 原子事务"], ["API 授权", "各服务重复实现", "OAuth 2.0／JWT 与共享 Default-Deny 安全库"]],
          onboardingFlow: ["CRM Onboarding 事件", "创建 Legal Entity", "触发下游用户与权限开通", "校验用户与权限状态"],
          contributionTitle: "覆盖架构设计、功能交付与生产工程的核心贡献",
          contributions: [["设计后端服务与可靠 REST 集成", "在 40+ 个 Spring 服务的平台内定义服务边界和 OpenAPI 契约，并实现核心 User Service，包括 WebFlux / WebClient、校验、幂等、错误回传与显式超时。"], ["构建动态 React 工作流与 UI 平台", "实现 Metadata / Schema 驱动的权限分配和按需加载，并搭建支撑 5 个 React 应用的 Module Federation 框架及 Nginx 部署。"], ["设计一致的数据与开户流程", "为用户与权限设计带索引的 MongoDB 集合和生命周期原子更新，并将 CRM 事件连接至下游 Legal Entity、用户与权限开通。"], ["建设授权与生产工程控制", "共同设计 OAuth 2.0 / JWT 授权和共享 Default-Deny Spring Security 库，并加入自动化质量门禁、结构化诊断、Actuator 健康检查与 Kibana 故障排查。"]],
          scaleMetrics: [["已上线", "完整管理生命周期投入生产"], ["100+", "清理团队服务中的安全问题"], ["90%+", "自动化测试覆盖率"], ["Golden", "Citi Gratitude Award · 2024"]],
          deliveryTitle: "建立支撑生产运行的工程控制",
          deliverySummary: "在功能交付之外，我共同设计授权层，并将安全扫描、自动化测试、监控和回滚控制纳入持续交付流程。",
          migrationSteps: ["梳理历史配置", "客户分组", "映射至 Persona", "制定迁移规则", "验证并分批上线"],
          securityTracks: [["Authorization Server", "共同设计并实现，作为独立的授权平台能力。"], ["共享 Spring Security JAR", "在各应用服务内执行 YAML 权限配置、JWT 角色与操作校验，以及 default-deny 策略。"]],
          securityTools: "SonarQube · Snyk · SAST · BDD / Cucumber · GitLab CI / Harness",
          deliveryPillars: [["统一 API 授权", "共同设计生成短期 JWT 并支持 Refresh Token 续期的 OAuth 2.0 Authorization Server，搭建执行 YAML Default-Deny 规则的共享 Spring Security JAR。"], ["将安全与质量检查纳入发布门禁", "把 SonarQube、Snyk、SAST 与自动化测试接入 GitLab CI / Harness，将问题修复作为生产发布条件。"], ["让生产行为可诊断", "增加结构化日志、Request ID 和 Actuator 健康检查，并使用 Kibana 定位 Kubernetes / OpenShift 中的跨服务故障。"]],
          ownership: "作为 Entitlements 的 Tech Lead / Senior Software Engineer，我共同设计领域模型与 Spring 技术架构，带领团队将端到端用户管理链路投入生产，并协调另外 5 个研发团队和 CRM 合作方完成集成。我直接管理 6 名中国工程师，并带领更广泛的 10 余人中印团队。",
          approach: ["交付完整管理生命周期——实现 Maker 创建、修改和删除请求，Checker 审批与拒绝，以及同步的权限变化。", "交付 Legal Entity 自动开户——将 CRM 事件连接至事件驱动流程，触发下游用户与权限开通。", "共同设计分阶段旧模型迁移——分析生产数据，为数千万级 Access Profile 定义转换规则，并让新旧模型在尚未完成的迁移期间共存。", "统一授权与生产诊断——把共享 Default-Deny 安全控制与自动化门禁、Request 级追踪、Actuator 健康检查和 Kibana 故障定位结合起来。"],
        },
        tags: ["Java / Spring Boot / Spring Cloud", "React 微前端", "OAuth 2.0 / Spring Security / JWT", "事件驱动微服务", "GitLab CI / Harness", "Kubernetes / OpenShift"],
      },
      {
        id: "velocity",
        title: "Citi Velocity Content & Search",
        role: "软件工程师 / 技术负责人 · 2017.07—2022.12",
        body: "带领 Citi Velocity 的 Content、Notification 和 Search 前端现代化；该平台服务全球 150 个国家近 10 万名机构投资者，并集成 200 多个业务应用。",
        result: "首屏等待与白屏时间缩短约 60%，完整交付 Search 体验，获得 2019 Golden 与 2021 Silver Award，并受邀在公司级技术大会分享架构与性能实践。",
        outcomeStatement: "完整交付端到端搜索体验",
        outcomes: [["≈60%", "首屏等待与白屏时间降幅"], ["完整交付", "覆盖搜索框 Typeahead 与完整搜索结果页面"], ["Golden + Silver", "Citi Gratitude Awards · 2019 / 2021 · 公司级技术大会分享"]],
        detail: {
          challenge: "Citi Velocity 服务全球 150 个国家近 10 万名机构投资者，并集成 200+ 应用。平台第二大流量入口需要统一呈现研报、行情、多媒体和应用，接入由不同团队维护的行情 Portlet，并解决旧前端加载缓慢的问题。",
          focus: "带领 Content、Notification 和 Search 的前端现代化",
          scope: "作为始终参与一线开发的技术负责人，我带领 4 名前端工程师负责 Content、Notification 和 Search，主导 Search UI 架构与性能方案，并协调 4 个数据团队的接口和发布依赖。",
          architectureTitle: "构建元数据驱动的 React 渲染",
          architectureSummary: "通过元数据驱动渲染统一异构结果，并用共享 FDC3 契约把搜索参数一致地传给由不同团队维护的行情 Portlet。",
          architectureNodes: [["将异构内容映射为可复用组件", "React · TypeScript · 策略模式 · 新数据类型快速接入"], ["通过 FDC3 统一 Portlet 集成", "共享契约 · 一致搜索参数 · 各团队独立维护"]],
          actionMeta: ["React · TypeScript · Strategy Pattern", "FDC3 · 跨应用 API · Events", "WebSocket · 实时通知", "Webpack · Code Splitting · CI/CD · Canary Release"],
          ownership: "作为始终参与一线开发的技术负责人，我带领 4 名前端工程师负责 Content、Notification 和 Search；主导 Search UI 架构与性能方案，完整交付从 Typeahead 到结果页面的体验，并协调 4 个数据团队的接口和发布依赖。",
          approach: ["构建可配置的 Search 渲染架构——通过 React、TypeScript 与 Strategy Pattern 将研报、行情和多媒体映射为可复用组件，使新增内容类型能够通过配置接入。", "统一 Search Portlet 集成——定义共享 FDC3 契约，把搜索参数传给由不同团队维护的行情 Portlet，为所有 Portlet 提供一致的接入模式。", "交付基于 WebSocket 的实时通知——带领完成 Notification 模块集成，实现消息实时推送并避免重复轮询。", "同步优化性能与发布安全——结合 Webpack Code Splitting、按需加载、Skeleton Screen、可复用 CI/CD 模板和 Canary Release，降低高流量入口的等待时间与发布风险。"],
        },
        tags: ["React / TypeScript", "元数据驱动 UI", "FDC3 API / Events", "WebSocket / 实时通知", "Webpack / Code Splitting", "CI/CD Templates / Canary Release"],
      },
      {
        id: "platform",
        title: "企业级 React 组件库",
        role: "核心开发 · 2018.07—2019.01",
        body: "参与从 0 到 1 建设 React / TypeScript 组件库，让 3 条业务线在保留各自界面风格的同时复用同一套核心实现。",
        result: "组件库支持 4 套界面规范和 8 种主题，被 3 条核心业务线采用，并通过统一组件接口和接入文档减少了重复的 UI 开发。",
        outcomeStatement: "把重复的 UI 开发沉淀为共享组件库",
        outcomes: [["3 条", "核心业务线采用组件库"], ["8 种主题", "覆盖 4 套界面规范"]],
        detail: {
          challenge: "3 条业务线分别维护自己的界面组件和主题样式，相似功能被反复开发，但每个产品又需要保留自己的视觉风格。",
          focus: "参与从 0 到 1 建设企业级 React 组件库",
          scope: "作为核心开发，我参与组件 API、主题扩展和接入文档的建设。",
          ownership: "作为组件库初建阶段的核心开发，我参与设计 React / TypeScript 实现和扩展机制，覆盖组件 API、主题体系与接入文档。",
          approach: ["构建可复用的 React 组件 API——围绕共同行为定义稳定的 TypeScript 接口，让业务团队复用组件时不必绑定某一条业务线的实现。", "通过主题配置支持多套设计规范——将组件核心逻辑与 SCSS 主题和配置分离，让一套实现支持 4 套界面规范与 8 种视觉主题。", "沉淀组件接入文档——提供 API 文档和开发手册，让业务团队可以自行配置和接入组件，避免重复开发同类功能。"],
          actionMeta: ["React · TypeScript · Component APIs", "SCSS · Theme Configuration · Design Systems", "API Documentation · Developer Guides"],
        },
        tags: ["React / TypeScript", "Shared Component Library", "Component APIs", "SCSS / Theming", "Multi-theme Design System", "Developer Documentation"],
      },
    ],
    galleryTabs: ["产品概览", "为什么要做", "首页体验", "支持工单"],
    galleryCaptions: ["辅食搭子把每日安排、食材排敏、不适回溯和冰箱库存整合进一个微信小程序。", "产品来自新手父母每天面对的真实问题：今天吃什么、哪些食材试过、宝宝不舒服可能与什么有关，以及冰箱里还剩什么。", "首页把今日安排、进度、不适记录、辅食建议和明日预告整理成一张可以直接执行的清单。", "获得用户授权后，支持后台仅展示排查和升级问题所需的信息，且不允许支持人员修改家庭过敏档案。"],
    galleryAlt: ["展示辅食搭子小程序及核心功能的产品概览海报", "说明新手父母四类日常辅食难题的插画海报", "展示每日辅食安排与不适记录功能的辅食搭子首页说明图", "展示工单队列与选中工单详情的辅食搭子 Web 支持控制台"],
    journeyTitle: "成长路径",
    journeyIntro: "我的核心经验来自花旗企业级系统的开发与技术管理；最近，我也在这套工程基础上继续拓展 AI Agent 的产品实践。",
    journey: [
      { period: "2017—至今", title: "花旗 · AVP / 高级软件工程师", body: "从一线开发逐步成长为 Tech Lead 和 People Manager，同时始终参与团队负责系统的核心开发。", stages: [
        ["现在", "一边做核心开发，一边带领团队", "负责关键的前后端功能，带领中印团队，并与全球多个团队合作，稳步推进复杂银行平台的改造。"],
        ["早期", "把前端做得更快、更好用", "重构高流量搜索体验，也参与建设供多条业务线复用的 React 组件库。"],
      ] },
      { period: "2026—至今", title: "将全栈经验拓展到 AI Agent", body: "独立设计并发布“辅食搭子”，将线上单 Agent DeepSeek 工作流、确定性安全边界和符合标准的 MCP 工具能力结合起来。", stages: [] },
      { period: "2013—2017", title: "厦门大学", body: "修读软件工程与经济学双学位，开始习惯同时从技术实现和业务价值理解产品。", stages: [] },
    ],
    contactTitle: "一起构建经得起长期使用的软件。",
    contactBody: "我希望寻找同时重视产品判断、实现质量和长期所有权的全栈工程岗位。",
    email: "发送邮件",
    source: "GitHub 主页",
    archive: "早期技术写作 · 2016—2018",
    footer: "史学佳设计与开发",
  },
} as const;
