export type Language = "en" | "zh";

export const content = {
  en: {
    name: "Xuejia Shi",
    role: "Senior Full-Stack Engineer",
    intro: "I build useful, dependable products across the stack.",
    location: "Shanghai, China",
    nav: ["About", "Journey", "Projects", "Contact"],
    aboutTitle: "About",
    about: [
      "Hi, I’m Xuejia, a full-stack engineer based in Shanghai. I studied Software Engineering and Economics at Xiamen University, which is probably why I tend to think about both how a product works and why it needs to exist in the first place.",
      "I’ve been at Citi since 2017, progressing from Software Engineer to AVP. Along the way, I’ve worked on institutional search, an enterprise React component library and a global corporate-banking entitlements system, with responsibilities spanning hands-on development, Scrum leadership, technical direction and people management.",
      "For the entitlements programme, I directly managed and coached six engineers in China and led a delivery team of more than 10 people across China and India. We worked with five other engineering teams distributed across the United States, Canada, Chile and India to migrate the platform in stages without interrupting critical user and approval journeys.",
      "More recently, I built Baby Food Buddy around a problem I ran into as a parent. I took it from an idea to a live product, building the WeChat mini-program, React operations console, APIs and cloud setup myself. It now has more than 300 users, and I keep improving it as I learn from how people actually use it.",
      "For my next role, I’d like to stay hands-on while helping shape both the product and the technical direction—and see important work through from the first idea to production.",
    ],
    projectsTitle: "Selected projects",
    projectsHint: "Select a project to explore the decisions behind it.",
    openProject: "Open project",
    closeProject: "Close project",
    backToPortfolio: "Back to portfolio",
    previousProject: "Previous project",
    nextProject: "Next project",
    projectPageLabel: "Project story",
    detailLabels: { challenge: "Context & challenge", ownership: "My ownership", approach: "How I approached it", impact: "Outcome" },
    featured: "Featured project",
    projects: [
      {
        id: "fushi",
        title: "Baby Food Buddy",
        role: "Independent Full-Stack / AI Engineer · 300+ users · Active development",
        body: "A live AI agent product for complementary-food planning and health tracking. DeepSeek works with real product data through controlled tools, deterministic rules protect food safety, and an AI-native workflow built around MCP and reusable Skills supports development and testing.",
        result: "Reached 300+ users by August 2026. Production DeepSeek, the support-ticket workflow and core parent journeys have been validated in real environments, with 90%+ automated test coverage across the API and React application.",
        outcomeStatement: "From independent build to real-world use",
        outcomes: [["300+", "cumulative users by Aug 2026"], ["Live", "AI meal planning, health tracking and user feedback are running in production"], ["90%+", "automated API and React test coverage"]],
        detail: {
          challenge: "Parents introducing solid foods repeatedly face three practical questions: what should the baby eat today, which foods have already been tried, and what may have caused a reaction. Meal plans, food-introduction records and pantry information are usually scattered. Baby Food Buddy brings them together and lets AI help only within explicit safety rules.",
          ownership: "I do more than use AI to assist development: I turn repeated development and testing workflows into reusable MCP tools and Skills. As the sole builder, I own the product and interaction design, implementation, testing, CloudBase deployment and production debugging across the WeChat mini-program, React console and Node.js APIs.",
          approach: ["Turned AI workflows into reusable tooling — packaged recurring development and testing tasks as 23 MCP tools, 10 resources, 3 prompts and reusable Skills for use across different workflows.", "Designed contract-first APIs — pnpm Workspaces, Express, oRPC and Zod give the React clients and Node.js services one source of truth for request, response and validation rules.", "Set verifiable boundaries for the AI agent — DeepSeek works with product data through controlled tools, while deterministic TypeScript rules protect food safety and require confirmation for irreversible actions.", "Validated product quality with automated tests — automated evaluation, Vitest, MSW, Supertest and Playwright cover safety, authentication and core parent journeys."],
        },
        tags: ["AI Agent", "AI-native", "TypeScript / React 19 / Router", "Node.js / Express", "oRPC / Zod", "TanStack Query / Zustand", "MCP / Skills", "Vitest / MSW / Playwright", "pnpm Workspaces / Vite / Tailwind"],
        link: "View source",
      },
      {
        id: "nextgen",
        title: "CitiDirect NextGen",
        role: "Tech Lead / Senior Software Engineer · 2023.01—Present",
        body: "Co-designed CitiDirect NextGen’s new user and entitlement model and Spring architecture, then led production delivery of the complete user-administration journey—from CRM-triggered Legal Entity onboarding to Persona-based access assignment.",
        result: "Put the end-to-end journey into production, eliminated more than 100 security findings before release, maintained 90%+ automated coverage and supported high-availability, biweekly delivery. Recognised individually with the 2024 Citi Gratitude Golden Award.",
        outcomeStatement: "Put the complete user-administration journey into production",
        outcomes: [["100+ → 0", "security findings eliminated before production"], ["Live", "Automated Legal Entity onboarding through Persona-based entitlement assignment, with high availability and biweekly releases"], ["2024", "Citi Gratitude Golden Award · individual recognition"]],
        detail: {
          casePages: ["Leadership & architecture", "Production engineering"],
          challenge: "User & Entitlements is CitiDirect’s shared access-control foundation for onboarding corporate users and managing access across transaction-banking services.",
          focus: "Co-designed the domain and full-stack architecture, then led production delivery.",
          scope: "As Tech Lead, I manage six engineers in China, lead the broader 10+ person China–India team, and coordinate integration with five other engineering teams and CRM partners.",
          architectureTitle: "A four-layer entitlement redesign",
          architectureSummary: "The change aligned access to clients’ Legal Entity structures, simplified entitlement assignment, automated onboarding and enabled federated corporate identity.",
          architectureColumns: ["Current state · CitiDirect BE", "NextGen model · CitiDirect V3"],
          architectureRows: [["Client structure", "Citi-defined Client Definition", "Legal Entity-aligned structure"], ["Access assignment", "Solution Package + Access Profile", "Persona + configurable permissions"], ["Onboarding", "Manual onboarding through GIAM", "Automated Legal Entity onboarding"], ["Identity", "Citi-specific identity", "OAuth 2.0 / OIDC federation"]],
          onboardingFlow: ["CRM onboarding event", "Create Legal Entity", "Create Security Managers & users", "Assign Persona entitlements"],
          contributionTitle: "Contributions across architecture, delivery and production engineering",
          contributions: [["Shaped the full-stack architecture", "Defined domain boundaries and API/event contracts across 40+ Spring Boot / Spring Cloud microservices, and built the React micro-frontend framework supporting five UI applications."], ["Engineered authorization and production controls", "Co-designed the OAuth 2.0 Authorization Server and shared Spring Security JAR, then embedded security gates, automated tests, monitoring and rollback into the delivery path."], ["Co-designed Persona-based access", "Connected Legal Entities, users, services and permissions through reusable Personas while retaining configurable options for complex clients."], ["Delivered automated Legal Entity onboarding", "Integrated CRM events to create Legal Entities and trigger user and entitlement provisioning, replacing manual setup with an end-to-end workflow."]],
          scaleMetrics: [["Live", "end-to-end administration journey in production"], ["100+ → 0", "security findings before production"], ["90%+", "automated test coverage"], ["Golden", "Citi Gratitude Award · 2024"]],
          deliveryTitle: "Engineered the controls required for production",
          deliverySummary: "Beyond feature delivery, I co-designed the authorization layer and embedded security, testing, monitoring and rollback controls into the delivery path.",
          migrationSteps: ["Review legacy setup", "Group clients", "Map to Personas", "Set migration rules", "Validate and roll out"],
          securityTracks: [["Authorization Server", "Co-designed and implemented as a separate authorization platform capability."], ["Shared Spring Security JAR", "Enforces YAML-configured API permissions, JWT roles and actions, and a default-deny policy inside application services."]],
          securityTools: "SonarQube · Snyk · CVM · SAST · GitLab CI / Harness",
          deliveryPillars: [["Standardized API authorization", "Co-designed an OAuth 2.0 Authorization Server for short-lived JWTs and built a shared Spring Security JAR that enforces YAML-defined, default-deny access rules across business services."], ["Embedded security gates", "Integrated SonarQube, Snyk and SAST into GitLab CI / Harness, making remediation a release condition before production."], ["Established test and recovery controls", "Maintained 90%+ automated coverage and established monitoring and rollback controls for Kubernetes / OpenShift deployments, supporting high availability and biweekly releases."]],
          ownership: "As Tech Lead / Senior Software Engineer for User & Entitlements, I co-designed the domain model and Spring architecture, led production delivery of the end-to-end user-administration journey, and coordinated five other engineering teams and CRM partners. I manage six engineers in China and lead the broader 10+ person China–India team.",
          approach: ["Simplified access assignment with reusable Personas — linked Legal Entities, users, services and permissions through predefined Personas while retaining configurable options for complex clients.", "Delivered automated Legal Entity onboarding — connected CRM events to an event-driven workflow that creates the Legal Entity and triggers user and entitlement provisioning without manual setup.", "Designed a data-driven phased migration — analysed production configurations, defined rules for active and retired records, and validated each rollout through API, log and data comparisons across tens of millions of Access Profiles.", "Standardised authorization and security gates — co-designed the Authorization Server and a shared Spring Security JAR with YAML-configured, JWT-based default-deny rules; integrated SonarQube, Snyk, CVM and SAST to reduce more than 100 findings to zero before production."],
        },
        tags: ["Java / Spring Boot / Spring Cloud", "React Micro-frontends", "OAuth 2.0 / Spring Security / JWT", "Event-driven Microservices", "GitLab CI / Harness", "Kubernetes / OpenShift"],
      },
      {
        id: "velocity",
        title: "Citi Velocity Content & Search",
        role: "Software Engineer / Technical Lead · 2017.07—2022.12",
        body: "Led frontend modernization across Content, Notification and Search on Citi Velocity, a platform serving nearly 100,000 institutional investors across 150 countries and integrating more than 200 business applications.",
        result: "Reduced initial wait and blank-screen time by about 60%, delivered the complete Search experience, received the 2019 Golden and 2021 Silver Awards, and presented the architecture and performance work at a company-wide engineering conference.",
        outcomeStatement: "Delivered the complete search experience",
        outcomes: [["≈60%", "reduction in initial wait and blank-screen time"], ["End-to-end", "Search-box typeahead and the complete results page"], ["Golden + Silver", "Citi Gratitude Awards · 2019 / 2021 · company-wide engineering conference speaker"]],
        detail: {
          challenge: "Citi Velocity serves nearly 100,000 institutional investors across 150 countries and integrates 200+ applications. Its second-highest-traffic entry point had to unify research, market data and multimedia, connect with trading workflows, and replace a slow legacy frontend.",
          focus: "Led frontend modernization across Content, Notification and Search",
          scope: "As a hands-on Technical Lead, I led four frontend engineers across Content, Notification and Search, owned the Search UI architecture and performance strategy, and coordinated API and release dependencies with four data teams.",
          architectureTitle: "Built metadata-driven React rendering",
          architectureSummary: "Metadata-driven rendering unified research, market data and multimedia results; FDC3 linked search with a separate trading panel.",
          architectureNodes: [["Mapped content to reusable components", "React · TypeScript · Strategy Pattern · extensible result types"], ["Connected search and trading through FDC3", "standardised APIs and events · shared instrument context"]],
          actionMeta: ["React · TypeScript · Strategy Pattern", "FDC3 · Cross-app APIs · Events", "WebSocket · Real-time Notifications", "Webpack · Code Splitting · CI/CD · Canary Release"],
          ownership: "As a hands-on Technical Lead, I led four frontend engineers responsible for Content, Notification and Search. I owned the Search UI architecture and performance strategy, delivered the complete experience from typeahead through the results page, and coordinated API and release dependencies with four data teams.",
          approach: ["Built configurable Search rendering — used React, TypeScript and the Strategy Pattern to map research, market data and multimedia into reusable components, allowing new content types to be introduced through configuration.", "Integrated Search and trading through FDC3 — defined cross-application context and event contracts so users could carry instrument context into a separate trading application and keep both applications synchronized.", "Delivered WebSocket-based notifications — led the Notification module integration to provide real-time user updates without repeated polling.", "Improved performance and release safety — combined Webpack code splitting, lazy loading and Skeleton Screens with reusable CI/CD templates and canary releases for a high-traffic entry point."],
        },
        tags: ["React / TypeScript", "Metadata-driven UI", "FDC3 APIs / Events", "WebSocket / Real-time Notifications", "Webpack / Code Splitting", "CI/CD Templates / Canary Release"],
      },
      {
        id: "platform",
        title: "Enterprise React Component Library",
        role: "Core Developer · 2018.07—2019.01",
        body: "Helped build a React / TypeScript component library from the ground up so three business lines could reuse the same implementation while preserving their own interface styles.",
        result: "The library supported four interface standards and eight themes, was adopted by three core business lines, and reduced duplicate UI work through consistent component APIs and adoption guidance.",
        outcomeStatement: "Turned duplicated UI work into a shared component library",
        outcomes: [["3", "core business lines adopted the library"], ["8 themes", "across four interface standards"]],
        detail: {
          challenge: "Three business lines maintained their own UI components and themes, so similar features were repeatedly rebuilt even though each product still needed to preserve its own visual identity.",
          focus: "Helped build a shared React component library from the ground up",
          scope: "As a core developer, I worked on component APIs, theme extensibility and adoption documentation.",
          ownership: "As a core developer during the library’s initial build, I helped shape its React / TypeScript implementation and extension model, covering component APIs, themes and adoption documentation.",
          approach: ["Built reusable React component APIs — defined shared behaviour and stable TypeScript interfaces so teams could reuse components without coupling them to one business line.", "Supported multiple design systems through themes — separated core component logic from SCSS themes and configuration, supporting four interface standards and eight visual themes on one implementation.", "Documented component adoption — provided API references and developer guides so teams could configure and adopt components without rebuilding the same solutions."],
          actionMeta: ["React · TypeScript · Component APIs", "SCSS · Theme Configuration · Design Systems", "API Documentation · Developer Guides"],
        },
        tags: ["React / TypeScript", "Shared Component Library", "Component APIs", "SCSS / Theming", "Multi-theme Design System", "Developer Documentation"],
      },
    ],
    galleryTabs: ["Product overview", "Why it matters", "Home experience", "Support console"],
    galleryCaptions: [
      "Baby Food Buddy brings meal planning, food-introduction tracking, reaction history and pantry management into one mini-program.",
      "The product grew from the small but demanding questions parents face every day: what to cook, what has been tried, what may have caused a reaction and what is still in the fridge.",
      "The home screen turns today’s meals, progress, reaction logging, suggestions and tomorrow’s plan into one practical checklist.",
      "With user consent, the support console exposes only the diagnostics needed to investigate and escalate issues—without allowing staff to edit family allergy data.",
    ],
    galleryAlt: ["Baby Food Buddy product overview poster showing the mini-program and its core features", "Illustrated poster explaining four everyday complementary-feeding challenges for parents", "Baby Food Buddy home-screen guide showing daily meal and reaction-tracking features", "Baby Food Buddy web support console showing the case queue and selected case details"],
    journeyTitle: "Engineering journey",
    journeyIntro: "My core experience comes from building and leading enterprise systems at Citi; more recently, I have extended that foundation by taking an AI agent product from idea to real-world use.",
    journey: [
      { period: "2017—Present", title: "Citi · AVP / Senior Software Engineer", body: "Grew from an individual contributor into a Tech Lead and people manager, while staying hands-on with the systems my teams deliver.", stages: [
        ["Today", "Building and leading across the stack", "Develop core backend and frontend features, guide a China–India team, and work with global partners to move a complex banking platform forward safely."],
        ["Earlier years", "Making front ends faster and easier to build", "Rebuilt a high-traffic search experience and helped create reusable React components for several business lines."],
      ] },
      { period: "2026—Now", title: "Extending my full-stack work into AI agents", body: "Designed and launched Baby Food Buddy, combining a user-facing AI agent with an AI-native workflow for building, testing and iteration.", stages: [] },
      { period: "2013—2017", title: "Xiamen University", body: "Studied Software Engineering and Economics, learning to look at products from both a technical and business perspective.", stages: [] },
    ],
    contactTitle: "Let’s build something dependable.",
    contactBody: "I’m interested in full-stack engineering roles where product judgment, implementation quality and long-term ownership all matter.",
    email: "Email me",
    source: "GitHub profile",
    archive: "Writing archive · 2016—2018",
    footer: "Designed and built by Xuejia Shi",
  },
  zh: {
    name: "史学佳",
    role: "高级全栈工程师",
    intro: "我是一名全栈工程师，喜欢把复杂的问题做成清晰、可靠、真正有人使用的产品。",
    location: "中国上海",
    nav: ["关于", "成长路径", "项目", "联系"],
    aboutTitle: "关于我",
    about: [
      "你好，我是史学佳，一名在上海工作的全栈工程师。我本科毕业于厦门大学，拥有软件工程和经济学双学位。这样的学习背景让我在做技术方案时，不只关注功能怎么实现，也会先理解它解决的业务问题，以及最终使用它的人。",
      "2017 年加入花旗后，我从软件工程师逐步成长为 AVP。一路上，我参与过机构搜索、企业级 React 组件库和全球企业网银权限系统的建设，职责也从一线开发扩展到 Scrum Team Lead、Tech Lead 和团队管理。",
      "在权限系统项目中，我直接管理和辅导 6 名中国工程师，并带领由中国和印度成员组成的 10 余人交付团队。我们与分布在美国、加拿大、智利和印度的另外 5 个研发团队协作，分阶段完成平台迁移，同时保证关键的用户与审批流程不中断。",
      "最近，我把实际育儿过程中遇到的需求做成了“辅食搭子”。从微信小程序、React 运营后台到 API、云端部署和线上排障，整个产品都由我独立设计和开发，目前已有 300 多名用户。相比只完成一个演示项目，我更享受把想法真正发布出去，再根据实际使用持续改进的过程。",
      "我希望下一份工作仍然能够让我保持 Hands-on：既参与产品和技术决策，也能亲自把重要功能做出来并负责到底。",
    ],
    projectsTitle: "精选项目",
    projectsHint: "选择一个项目，查看它背后的工程判断。",
    openProject: "打开项目",
    closeProject: "关闭项目",
    backToPortfolio: "返回作品集",
    previousProject: "上一个项目",
    nextProject: "下一个项目",
    projectPageLabel: "项目详解",
    detailLabels: { challenge: "背景与挑战", ownership: "我的职责", approach: "解决方式", impact: "项目结果" },
    featured: "重点项目",
    projects: [
      {
        id: "fushi",
        title: "辅食搭子",
        role: "独立全栈 / AI 工程师 · 300+ 用户 · 持续迭代中",
        body: "一款已经上线的 AI Agent 辅食规划与健康记录产品。DeepSeek 通过受控工具处理真实产品数据，确定性规则守住食物安全边界，并以 MCP 和可复用 Skills 支持 AI-native 开发与测试。",
        result: "截至 2026 年 8 月累计用户超过 300 人；线上 DeepSeek、支持工单流程和家长核心使用路径均已在真实环境完成验证，API 与 React 自动化测试覆盖率超过 90%。",
        outcomeStatement: "从独立开发走到真实用户使用",
        outcomes: [["300+", "截至 2026 年 8 月累计用户"], ["线上验证", "AI 辅食规划、健康记录与用户反馈功能均已投入真实使用"], ["90%+", "API 与 React 自动化测试覆盖"]],
        detail: {
          challenge: "新手父母每天都要反复确认：今天吃什么、哪些食材已经尝试过、宝宝不舒服可能和什么有关。菜单、排敏记录和冰箱库存通常分散在不同地方，既难安排，也难回溯。“辅食搭子”把这些信息放在一起，并让 AI 只在明确的安全规则内提供帮助。",
          ownership: "我不只使用 AI 辅助开发，也把重复的开发与测试流程封装成可复用的 MCP Tools 和 Skills。作为独立开发者，我负责产品与交互设计、前后端实现、测试、CloudBase 部署和线上排障，覆盖微信小程序、React 后台与 Node.js API。",
          approach: ["把 AI 工作流沉淀为可复用工具——将反复出现的开发与测试任务封装为 23 个 MCP Tools、10 个 Resources、3 个 Prompts 和可复用 Skills，供不同工作流直接调用。", "先定义接口契约，再实现前后端功能——通过 pnpm Workspaces、Express、oRPC 和 Zod，让 React 客户端与 Node.js 服务共用请求、返回和校验规则。", "为 AI Agent 设置可验证的安全边界——DeepSeek 只能通过受控工具操作产品数据，确定性 TypeScript 规则负责食物安全，不可逆操作必须由用户确认。", "用自动化测试验证产品质量——自动化评测、Vitest、MSW、Supertest 和 Playwright 覆盖安全、鉴权及家长核心路径。"],
        },
        tags: ["AI Agent", "AI-native", "TypeScript / React 19 / Router", "Node.js / Express", "oRPC / Zod", "TanStack Query / Zustand", "MCP / Skills", "Vitest / MSW / Playwright", "pnpm Workspaces / Vite / Tailwind"],
        link: "查看源码",
      },
      {
        id: "nextgen",
        title: "CitiDirect NextGen",
        role: "Tech Lead / Senior Software Engineer · 2023.01—至今",
        body: "共同设计 CitiDirect NextGen 新用户与权限模型及 Spring 技术架构，并带领团队将完整用户管理链路投入生产：从 CRM 触发的 Legal Entity 全自动开户，贯通至基于 Persona 的权限分配。",
        result: "端到端链路已投入生产；发布前将 100+ 个安全问题清零，自动化测试覆盖率保持在 90% 以上，并持续支持高可用、双周生产发布。个人获得 2024 年 Citi Gratitude Golden Award。",
        outcomeStatement: "将完整用户管理链路投入生产",
        outcomes: [["100+ → 0", "生产发布前清零安全问题"], ["已上线", "从 Legal Entity 全自动开户贯通至 Persona 权限分配，并保持高可用与双周发布"], ["2024", "Citi Gratitude Golden Award · 个人获奖"]],
        detail: {
          casePages: ["领导力与架构", "生产工程"],
          challenge: "User & Entitlements 是 CitiDirect 的统一访问控制基础能力，负责企业客户用户开通及交易银行服务权限管理。",
          focus: "共同设计领域模型与全栈架构，并带领团队完成生产交付。",
          scope: "作为 Tech Lead，我直接管理 6 名中国工程师，带领更广泛的 10 余人中印团队，并协调另外 5 个研发团队和 CRM 合作方完成集成。",
          architectureTitle: "四层权限体系升级",
          architectureSummary: "这次升级同时调整客户组织方式、权限分配、开户流程与身份认证；Persona 是新权限模型的一部分，而不是全部。",
          architectureColumns: ["现有模式 · CitiDirect BE", "NextGen 模式 · CitiDirect V3"],
          architectureRows: [["客户结构", "花旗内部 Client Definition", "按客户 Legal Entity 组织"], ["权限分配", "Solution Package + Access Profile", "Persona + 可配置权限"], ["开户流程", "通过 GIAM 人工开户", "Legal Entity 自动开户"], ["身份认证", "必须使用花旗身份", "OAuth 2.0 / OIDC 企业身份联合"]],
          onboardingFlow: ["CRM onboarding 事件", "创建 Legal Entity", "创建 Security Manager 与交易用户", "分配 Persona 权限"],
          contributionTitle: "覆盖架构设计、功能交付与生产工程的核心贡献",
          contributions: [["共同设计全栈技术架构", "规划 40+ 个 Spring Boot／Spring Cloud 微服务的领域边界及 API／事件契约，并搭建支撑 5 个 UI 应用的 React 微前端框架。"], ["构建授权与生产工程控制", "共同设计 OAuth 2.0 Authorization Server 与共享 Spring Security JAR，并将安全门禁、自动化测试、监控和回滚纳入交付流程。"], ["共同设计基于 Persona 的权限模型", "通过可复用 Persona 连接 Legal Entity、用户、服务与权限，同时为复杂客户保留可配置能力。"], ["交付 Legal Entity 全自动开户", "接入 CRM 事件，自动创建 Legal Entity 并触发用户与权限开通，以端到端自动化流程替代人工设置。"]],
          scaleMetrics: [["已上线", "端到端用户管理链路投入生产"], ["100+ → 0", "生产发布前安全问题"], ["90%+", "自动化测试覆盖率"], ["Golden", "Citi Gratitude Award · 2024"]],
          deliveryTitle: "建立支撑生产运行的工程控制",
          deliverySummary: "在功能交付之外，我共同设计授权层，并将安全扫描、自动化测试、监控和回滚控制纳入持续交付流程。",
          migrationSteps: ["梳理历史配置", "客户分组", "映射至 Persona", "制定迁移规则", "验证并分批上线"],
          securityTracks: [["Authorization Server", "共同设计并实现，作为独立的授权平台能力。"], ["共享 Spring Security JAR", "在各应用服务内执行 YAML 权限配置、JWT 角色与操作校验，以及 default-deny 策略。"]],
          securityTools: "SonarQube · Snyk · CVM · SAST · GitLab CI / Harness",
          deliveryPillars: [["统一 API 授权", "共同设计生成短期 JWT 的 OAuth 2.0 Authorization Server，并搭建共享 Spring Security JAR，在业务服务中执行 YAML 配置的 default-deny 权限规则。"], ["将安全检查纳入发布门禁", "把 SonarQube、Snyk 和 SAST 接入 GitLab CI / Harness，将安全问题修复作为生产发布前的必要条件。"], ["建立测试与故障恢复控制", "保持 90%+ 自动化测试覆盖，并为 Kubernetes／OpenShift 部署建立监控和回滚控制，支持高可用与双周发布。"]],
          ownership: "作为 User & Entitlements 的 Tech Lead / Senior Software Engineer，我共同设计领域模型与 Spring 技术架构，带领团队将端到端用户管理链路投入生产，并协调另外 5 个研发团队和 CRM 合作方完成集成。我直接管理 6 名中国工程师，并带领更广泛的 10 余人中印团队。",
          approach: ["通过可复用 Persona 简化权限分配——用预定义 Persona 连接 Legal Entity、用户、服务与权限，同时为复杂客户保留可配置能力。", "交付 Legal Entity 全自动开户——将 CRM 事件接入事件驱动流程，自动创建 Legal Entity 并触发用户与权限开通，替代人工设置。", "共同设计数据驱动的分阶段迁移——分析生产配置，为在用和已退役记录制定迁移规则，并通过 API、日志与数据比对验证数千万级 Access Profile 的每个发布阶段。", "统一 API 授权并建设安全门禁——共同设计 Authorization Server 和共享 Spring Security JAR，通过 YAML 配置、JWT 角色与操作权限执行默认拒绝策略；将 SonarQube、Snyk、CVM 和 SAST 接入流水线，把 100+ 个安全问题在生产发布前降至零。"],
        },
        tags: ["Java / Spring Boot / Spring Cloud", "React 微前端", "OAuth 2.0 / Spring Security / JWT", "事件驱动微服务", "GitLab CI / Harness", "Kubernetes / OpenShift"],
      },
      {
        id: "velocity",
        title: "Citi Velocity Content & Search",
        role: "软件工程师 / 技术负责人 · 2017.07—2022.12",
        body: "带领 Citi Velocity 的 Content、Notification 和 Search 前端现代化；该平台服务全球 150 个国家近 10 万名机构投资者，并集成 200 多个业务应用。",
        result: "首屏等待与白屏时间缩短约 60%，完整交付 Search 体验，获得 2019 Golden 与 2021 Silver Award，并受邀在公司级技术大会分享架构与性能实践。",
        outcomeStatement: "完整交付端到端搜索体验",
        outcomes: [["≈60%", "首屏等待与白屏时间降幅"], ["完整交付", "覆盖搜索框 Typeahead 与完整搜索结果页面"], ["Golden + Silver", "Citi Gratitude Awards · 2019 / 2021 · 公司级技术大会分享"]],
        detail: {
          challenge: "Citi Velocity 服务全球 150 个国家近 10 万名机构投资者，并集成 200+ 应用。平台第二大流量入口需要统一呈现研报、行情和多媒体内容，与交易流程联动，并解决旧前端加载缓慢的问题。",
          focus: "带领 Content、Notification 和 Search 的前端现代化",
          scope: "作为始终参与一线开发的技术负责人，我带领 4 名前端工程师负责 Content、Notification 和 Search，主导 Search UI 架构与性能方案，并协调 4 个数据团队的接口和发布依赖。",
          architectureTitle: "构建元数据驱动的 React 渲染",
          architectureSummary: "通过元数据驱动渲染将研报、行情和多媒体结果映射到可复用组件，并使用 FDC3 连接搜索模块与独立交易面板。",
          architectureNodes: [["将异构内容映射为可复用组件", "React · TypeScript · 策略模式 · 新数据类型快速接入"], ["通过 FDC3 联动交易应用", "标准化 API 与事件 · 证券上下文和状态同步"]],
          actionMeta: ["React · TypeScript · Strategy Pattern", "FDC3 · 跨应用 API · Events", "WebSocket · 实时通知", "Webpack · Code Splitting · CI/CD · Canary Release"],
          ownership: "作为始终参与一线开发的技术负责人，我带领 4 名前端工程师负责 Content、Notification 和 Search；主导 Search UI 架构与性能方案，完整交付从 Typeahead 到结果页面的体验，并协调 4 个数据团队的接口和发布依赖。",
          approach: ["构建可配置的 Search 渲染架构——通过 React、TypeScript 与 Strategy Pattern 将研报、行情和多媒体映射为可复用组件，使新增内容类型能够通过配置接入。", "通过 FDC3 集成 Search 与交易应用——定义跨应用上下文和事件契约，让用户可以把搜索结果中的证券信息传递至独立交易应用并保持两端状态同步。", "交付基于 WebSocket 的实时通知——带领完成 Notification 模块集成，实现消息实时推送并避免重复轮询。", "同步优化性能与发布安全——结合 Webpack Code Splitting、按需加载、Skeleton Screen、可复用 CI/CD 模板和 Canary Release，降低高流量入口的等待时间与发布风险。"],
        },
        tags: ["React / TypeScript", "元数据驱动 UI", "FDC3 API / Events", "WebSocket / 实时通知", "Webpack / Code Splitting", "CI/CD Templates / Canary Release"],
      },
      {
        id: "platform",
        title: "企业级 React 组件库",
        role: "核心开发 · 2018.07—2019.01",
        body: "参与从 0 到 1 建设 React / TypeScript 组件库，让 3 条业务线在保留各自界面风格的同时复用同一套核心实现。",
        result: "组件库支持 4 套界面规范和 8 种主题，被 3 条核心业务线采用，并通过统一组件接口和接入文档减少了重复的 UI 开发。",
        outcomeStatement: "把重复的 UI 开发沉淀为共享组件库",
        outcomes: [["3 条", "核心业务线采用组件库"], ["8 种主题", "覆盖 4 套界面规范"]],
        detail: {
          challenge: "3 条业务线分别维护自己的界面组件和主题样式，相似功能被反复开发，但每个产品又需要保留自己的视觉风格。",
          focus: "参与从 0 到 1 建设企业级 React 组件库",
          scope: "作为核心开发，我参与组件 API、主题扩展和接入文档的建设。",
          ownership: "作为组件库初建阶段的核心开发，我参与设计 React / TypeScript 实现和扩展机制，覆盖组件 API、主题体系与接入文档。",
          approach: ["构建可复用的 React 组件 API——围绕共同行为定义稳定的 TypeScript 接口，让业务团队复用组件时不必绑定某一条业务线的实现。", "通过主题配置支持多套设计规范——将组件核心逻辑与 SCSS 主题和配置分离，让一套实现支持 4 套界面规范与 8 种视觉主题。", "沉淀组件接入文档——提供 API 文档和开发手册，让业务团队可以自行配置和接入组件，避免重复开发同类功能。"],
          actionMeta: ["React · TypeScript · Component APIs", "SCSS · Theme Configuration · Design Systems", "API Documentation · Developer Guides"],
        },
        tags: ["React / TypeScript", "Shared Component Library", "Component APIs", "SCSS / Theming", "Multi-theme Design System", "Developer Documentation"],
      },
    ],
    galleryTabs: ["产品概览", "为什么要做", "首页体验", "支持工单"],
    galleryCaptions: ["辅食搭子把每日安排、食材排敏、不适回溯和冰箱库存整合进一个微信小程序。", "产品来自新手父母每天面对的真实问题：今天吃什么、哪些食材试过、宝宝不舒服可能与什么有关，以及冰箱里还剩什么。", "首页把今日安排、进度、不适记录、辅食建议和明日预告整理成一张可以直接执行的清单。", "获得用户授权后，支持后台仅展示排查和升级问题所需的信息，且不允许支持人员修改家庭过敏档案。"],
    galleryAlt: ["展示辅食搭子小程序及核心功能的产品概览海报", "说明新手父母四类日常辅食难题的插画海报", "展示每日辅食安排与不适记录功能的辅食搭子首页说明图", "展示工单队列与选中工单详情的辅食搭子 Web 支持控制台"],
    journeyTitle: "成长路径",
    journeyIntro: "我的核心经验来自花旗企业级系统的开发与技术管理；最近，我也在这套工程基础上继续拓展 AI Agent 的产品实践。",
    journey: [
      { period: "2017—至今", title: "花旗 · AVP / 高级软件工程师", body: "从一线开发逐步成长为 Tech Lead 和 People Manager，同时始终参与团队负责系统的核心开发。", stages: [
        ["现在", "一边做核心开发，一边带领团队", "负责关键的前后端功能，带领中印团队，并与全球多个团队合作，稳步推进复杂银行平台的改造。"],
        ["早期", "把前端做得更快、更好用", "重构高流量搜索体验，也参与建设供多条业务线复用的 React 组件库。"],
      ] },
      { period: "2026—至今", title: "将全栈经验拓展到 AI Agent", body: "独立设计并发布“辅食搭子”，将面向用户的 AI Agent 与用于开发、测试和迭代的 AI-native 工作流结合起来。", stages: [] },
      { period: "2013—2017", title: "厦门大学", body: "修读软件工程与经济学双学位，开始习惯同时从技术实现和业务价值理解产品。", stages: [] },
    ],
    contactTitle: "一起构建经得起长期使用的软件。",
    contactBody: "我希望寻找同时重视产品判断、实现质量和长期所有权的全栈工程岗位。",
    email: "发送邮件",
    source: "GitHub 主页",
    archive: "早期技术写作 · 2016—2018",
    footer: "史学佳设计与开发",
  },
} as const;
