export type Language = "en" | "zh";

export const content = {
  en: {
    name: "Xuejia Shi",
    role: "Senior Full-Stack Engineer",
    intro: "I build useful, dependable products across the stack.",
    location: "Shanghai, China",
    nav: ["About", "Journey", "Projects", "Contact"],
    aboutTitle: "About",
    about: [
      "Hi, I’m Xuejia, a full-stack engineer based in Shanghai. I studied Software Engineering and Economics at Xiamen University, which is probably why I tend to think about both how a product works and why it needs to exist in the first place.",
      "I’ve been at Citi since 2017. I started as a front-end engineer and grew into a Senior Software Engineer and Tech Lead, working on institutional search, shared React platforms and a global corporate-banking entitlements system. I still like being close to the code, but over time my role also grew to include people management and delivery leadership.",
      "For the entitlements programme, I was the people manager for engineers based in China and led an agile team of more than 10 people across China and India. We worked alongside five other teams in the United States, India, Canada and Chile to bring the new platform into production.",
      "More recently, I built Baby Food Buddy around a problem I ran into as a parent. I took it from an idea to a live product, building the WeChat mini-program, React operations console, APIs and cloud setup myself. It now has more than 300 users, and I keep improving it as I learn from how people actually use it.",
      "For my next role, I’d like to stay hands-on while helping shape both the product and the technical direction—and see important work through from the first idea to production.",
    ],
    projectsTitle: "Selected projects",
    projectsHint: "Select a project to explore the decisions behind it.",
    openProject: "Open project",
    closeProject: "Close project",
    backToPortfolio: "Back to portfolio",
    previousProject: "Previous project",
    nextProject: "Next project",
    projectPageLabel: "Project story",
    detailLabels: { challenge: "Context & challenge", ownership: "My ownership", approach: "How I approached it", impact: "Outcome" },
    featured: "Featured project",
    projects: [
      {
        id: "fushi",
        title: "Baby Food Buddy",
        role: "Independent Full-Stack / AI Engineer · 2026 · Active development",
        body: "A released complementary-food planning and health-tracking product for families with babies aged 4–24 months. It connects a WeChat mini-program, React 19 operations and safety console, Express / oRPC API, MCP server, and reusable AI-assisted engineering workflows.",
        result: "Reached 300+ users by August 2026. API / React line coverage reached 96.63% / 89.88%, while deterministic safety controls, auditable traces, offline-capable agent tooling, and production validation made the complete delivery path inspectable.",
        detail: {
          challenge: "A released family nutrition product has to remain simple for parents while enforcing food-safety rules, privacy boundaries, authenticated operations, and traceable decisions across the mini-program, cloud services, operations console, and AI-assisted workflows.",
          ownership: "I owned the end-to-end delivery independently—from product and interaction design through contracts, implementation, testing, CI, cloud deployment, and production debugging—across the WeChat mini-program, React console, Node.js APIs, and reusable agent tooling.",
          approach: ["Structured the codebase as a pnpm TypeScript workspace and extracted shared Zod / oRPC contracts into a reusable package. The Express OpenAPI service and React 19 OpenAPILink client consume the same definitions, eliminating duplicated frontend and backend API types.", "Built the React 19 operations console with React Router, TanStack Query, Zustand, Vite, and Tailwind CSS, adding CloudBase login, automatic Bearer-token injection, fail-closed sessions, and responsive request states.", "Exposed deterministic domain capabilities through 23 MCP tools, 10 resources, and 3 prompts, then codified safety-sensitive changes in a reusable Skill and AGENTS.md workflow. Anthropic, OpenAI-compatible, and mock adapters support both live and offline development.", "Kept food safety, allergy-state transitions, and irreversible operations outside the LLM path. Zod-enforced confirmations, centralised safety checks, auditable ruleTrace outputs, and explicit AI-context consent protect high-risk boundaries.", "Used Vitest, MSW, Supertest, and Playwright to verify contracts, auth failures, safety blocks, retries, and parent reaction handling. The suite passed 72 API, 40 React/MSW, 3 Chromium E2E, 46 MCP smoke, and 11 integration checks under TypeScript strict and noImplicitAny.", "Deployed isolated CloudBase functions, a transactional case store, and the operations console with token validation, server-side roles, and CORS controls. After tracing empty cloud snapshots overwriting local data, I redesigned the AI flow around request-scoped memory and field-level deltas, validated live DeepSeek and the support lifecycle, and configured Node 20 / 22 GitHub Actions."],
        },
        tags: ["TypeScript", "React 19", "Express", "oRPC", "Zod", "TanStack Query", "Zustand", "CloudBase", "Vitest", "MSW", "Playwright", "MCP", "GitHub Actions"],
        link: "View source",
      },
      {
        id: "nextgen",
        title: "CitiDirect NextGen",
        role: "Tech Lead / Senior Software Engineer · 2023—2025",
        body: "Led the user-entitlements workstream in a global platform modernisation while the legacy and new systems ran side by side. Managed engineers in China, led a 10+ person delivery team across China and India, and worked with five other international teams.",
        result: "Took full ownership of the user-entitlements module, kept critical journeys highly available throughout migration, sustained 90%+ automated coverage for core modules, and received the 2024 Citi Gratitude Golden Award.",
        detail: {
          challenge: "CitiDirect serves corporate clients in 96 countries and processes approximately US$4 trillion each day. Its entitlements platform had to be modernised while legacy and new systems ran in parallel, with no compromise to security controls, approval integrity, or service continuity.",
          ownership: "As Tech Lead / Senior Software Engineer, I owned the user-entitlements module and managed the engineers based in China. I also led an agile delivery team of more than 10 people across China and India, working with five other product and engineering teams in the United States, India, Canada and Chile on the phased migration.",
          approach: ["Worked with product, security, and operations teams to translate onboarding, authorisation, approval controls, and access rules into API contracts, data models, migration stages, and implementable engineering tasks.", "Hands-on designed and implemented the React / Webpack Module Federation host, shared dependencies, and core entitlements UI so participating teams could develop, test, and release independently.", "Delivered REST APIs with OIDC, OAuth 2.0, and JWT plus a Kafka / MongoDB coexistence layer, using API, log, and data validation to investigate anomalies and preserve migration integrity.", "Integrated BDD / Cucumber into CI/CD, containerised services with Docker, deployed on Kubernetes / OpenShift, and established regression coverage, release checks, and operational guidance for critical authorisation journeys."],
        },
        tags: ["React", "Module Federation", "REST APIs", "OIDC", "OAuth 2.0", "JWT", "Kafka", "MongoDB", "Docker", "Kubernetes / OpenShift"],
      },
      {
        id: "velocity",
        title: "Citi Velocity Search",
        role: "Core Front-End Engineer / Scrum Team Lead · 2017—2023",
        body: "Rebuilt a high-traffic institutional search entry point serving nearly 100,000 users. Designed metadata-driven rendering for heterogeneous financial content and integrated independent trading experiences through FDC3.",
        result: "Reduced first-screen and white-screen time by about 60%, delivered four core production modules, and received the 2019 Citi Gratitude Golden Award for front-end architecture and performance engineering.",
        detail: {
          challenge: "Citi Velocity Search was the platform's second-largest traffic entry point, serving nearly 100,000 institutional investors. The rebuild had to absorb heterogeneous financial content, interoperate with independent trading panels, and remove the rendering delays of the legacy front end.",
          ownership: "As a core front-end engineer and Scrum Team Lead, I led the front-end rebuild, owned the UI architecture and performance strategy, and delivered four production modules.",
          approach: ["Used React, TypeScript, the Strategy Pattern, and metadata-driven rendering to decouple content components and reduce the effort required to onboard new financial data types.", "Standardised cross-application APIs with FDC3 in the micro-frontend architecture, enabling interoperability and real-time state synchronisation with independent trading panels.", "Combined Webpack code splitting, on-demand loading, Skeleton Screens, and multi-version canary releases to reduce legacy white-screen delays without introducing an all-at-once rollout risk."],
        },
        tags: ["React", "TypeScript", "Strategy Pattern", "FDC3", "Webpack", "Code Splitting", "Canary Release"],
      },
      {
        id: "platform",
        title: "React Platform & Developer Productivity",
        role: "Core Developer · 2018—2025",
        body: "Built reusable React / TypeScript foundations and engineering guidance for distributed teams, turning repeated interface and release work into shared assets.",
        result: "Established a shared component and delivery foundation supporting four design systems, eight themes, and three core business lines, while reducing repeated UI and release work across distributed teams.",
        detail: {
          challenge: "Distributed teams across several products were repeatedly rebuilding the same interface behaviours, theming mechanisms, documentation, and release setup, while each business line still needed to preserve its own visual system.",
          ownership: "As a core developer, I helped build the React / TypeScript component library from the ground up and contributed the extension model, engineering standards, shared delivery templates, and adoption documentation.",
          approach: ["Designed shared component APIs around common behaviour and isolated product differences at the theme and configuration layers.", "Used React, TypeScript, and SCSS to support four design systems and eight themes without fragmenting the core implementation.", "Paired reusable components with CI/CD templates, code standards, API documentation, and developer guides so distributed teams could review, configure, and release consistently."],
        },
        tags: ["React", "TypeScript", "SCSS", "Design Systems", "Component APIs", "CI/CD", "Developer Documentation"],
      },
    ],
    galleryTabs: ["Mini-program", "Support workflow", "Safety rules"],
    galleryCaptions: [
      "The family-facing daily experience in WeChat Developer Tools.",
      "A privacy-minimised support queue built around structured diagnostic evidence.",
      "A deterministic pre-release rule check with traceable decisions.",
    ],
    galleryAlt: ["Baby Food Buddy WeChat mini-program home screen", "Baby Food Buddy household support console", "Baby Food Buddy safety rule validation console"],
    perspectiveTitle: "Explore the system",
    perspectives: [
      ["Family", "Plan meals, track food introduction and report a concern without leaving the product."],
      ["Operations", "Triage authorised, metadata-only cases without gaining permission to edit family health records."],
      ["Engineering", "Share typed contracts, deterministic rules, tests and reusable MCP / Skill workflows."],
    ],
    evidence: [["300+", "users · Aug 2026"], ["96.63%", "API line coverage"], ["89.88%", "React line coverage"]],
    journeyTitle: "Engineering journey",
    journeyIntro: "From front-end systems to platform leadership and independent product work, my scope has expanded while the thread stayed consistent: make complex systems understandable, deliverable and reusable.",
    journey: [
      { period: "2026—Now", title: "Independent full-stack product practice", body: "Built and operate Baby Food Buddy across product design, TypeScript full-stack engineering, AI workflows and cloud delivery.", stages: [] },
      { period: "2017—Present", title: "Citi · Senior Software Engineer / Tech Lead", body: "Progressed from core front-end engineering to full-stack delivery and technical leadership on global institutional platforms.", stages: [
        ["Recent stage", "Platform technical leadership", "Secure entitlements, API contracts, migration architecture, quality strategy and cross-border delivery."],
        ["Foundation stage", "Front-end systems engineering", "React architecture, institutional search, micro-frontends, FDC3 integration and performance engineering."],
      ] },
      { period: "2013—2017", title: "Software engineering foundation", body: "Software Engineering and Economics dual degree at Xiamen University.", stages: [] },
    ],
    contactTitle: "Let’s build something dependable.",
    contactBody: "I’m interested in full-stack engineering roles where product judgment, implementation quality and long-term ownership all matter.",
    email: "Email me",
    source: "GitHub profile",
    archive: "Writing archive · 2016—2018",
    footer: "Designed and built by Xuejia Shi",
  },
  zh: {
    name: "史学佳",
    role: "高级全栈工程师",
    intro: "我是一名全栈工程师，喜欢把复杂的问题做成清晰、可靠、真正有人使用的产品。",
    location: "中国上海",
    nav: ["关于", "成长路径", "项目", "联系"],
    aboutTitle: "关于我",
    about: [
      "你好，我是史学佳，一名在上海工作的全栈工程师。我本科毕业于厦门大学，拥有软件工程和经济学双学位。这样的学习背景让我在做技术方案时，不只关注功能怎么实现，也会先理解它解决的业务问题，以及最终使用它的人。",
      "2017 年加入花旗后，我从前端工程师逐步成长为 Senior Software Engineer 和 Tech Lead，参与过机构搜索、共享组件平台和全球企业网银权限系统的建设。除了持续写代码，我也是中国团队的 People Manager，并带领由中国和印度成员组成的 10 余人敏捷团队；项目期间还与分布在美国、印度、加拿大和智利的另外 5 个团队协作，共同完成系统交付。",
      "最近，我把实际育儿过程中遇到的需求做成了“辅食搭子”。从微信小程序、React 运营后台到 API、云端部署和线上排障，整个产品都由我独立设计和开发，目前已有 300 多名用户。相比只完成一个演示项目，我更享受把想法真正发布出去，再根据实际使用持续改进的过程。",
      "我希望下一份工作仍然能够让我保持 Hands-on：既参与产品和技术决策，也能亲自把重要功能做出来并负责到底。",
    ],
    projectsTitle: "精选项目",
    projectsHint: "选择一个项目，查看它背后的工程判断。",
    openProject: "打开项目",
    closeProject: "关闭项目",
    backToPortfolio: "返回作品集",
    previousProject: "上一个项目",
    nextProject: "下一个项目",
    projectPageLabel: "项目详解",
    detailLabels: { challenge: "背景与挑战", ownership: "我的职责", approach: "解决方式", impact: "项目结果" },
    featured: "重点项目",
    projects: [
      {
        id: "fushi",
        title: "辅食搭子",
        role: "独立全栈 / AI 工程师 · 2026 · 持续迭代中",
        body: "面向 4–24 月龄宝宝家庭、已经正式发布的辅食规划与健康记录产品。系统连接微信小程序、React 19 运营与安全控制台、Express / oRPC API、MCP Server，以及可复用的 AI 辅助开发工作流。",
        result: "截至 2026 年 8 月累计用户超过 300 人，API / React 行覆盖率达到 96.63% / 89.88%；确定性安全控制、可审计链路、支持离线开发的 Agent 工具和线上验收，让完整交付过程具备可验证的质量证据。",
        detail: {
          challenge: "面向家庭的产品需要让家长使用起来足够简单、安心，但正式运行的系统还必须同时守住食物安全、隐私、身份认证和操作边界，并确保小程序、云端服务、运营后台与 AI 工作流中的关键判断都能追溯。",
          ownership: "我独立负责从产品与交互设计到契约定义、开发、测试、CI、云端部署和生产排障的完整交付，覆盖微信小程序、React 运营后台、Node.js API，以及可复用的 Agent 开发工具。",
          approach: ["使用 pnpm Workspaces 组织 TypeScript Monorepo，将 Zod / oRPC 合约抽取为共享 Package；Express OpenAPI 服务与 React 19 的 OpenAPILink 客户端直接消费同一套定义，避免前后端重复维护接口类型。", "使用 React Router、TanStack Query、Zustand、Vite 与 Tailwind CSS 构建 React 19 运营控制台，并接入 CloudBase 登录、Bearer Token 自动注入、Fail-Closed 会话和完整的请求状态反馈。", "将确定性业务能力封装为 23 个 MCP Tools、10 个 Resources 和 3 个 Prompts，并把涉及安全的重复变更沉淀为可复用 Skill 与 AGENTS.md 工作流；通过 Anthropic、OpenAI-Compatible 和 Mock Provider 同时支持线上模型与无密钥离线开发。", "将食物安全、排敏状态变化和不可逆操作留在 LLM 路径之外，通过 Zod Literal Confirmation、统一安全检查、可审计 ruleTrace 与 AI 上下文明示授权保护高风险边界。", "使用 Vitest、MSW、Supertest 与 Playwright 覆盖契约、鉴权失败、安全拦截、重试和家长反应处置；通过 72 项 API、40 项 React/MSW、3 项 Chromium E2E、46 项 MCP 冒烟和 11 步集成检查，并将共享规则纳入 TypeScript strict 与 noImplicitAny 门禁。", "部署隔离的 CloudBase 云函数、事务工单和运营后台，并实施 Token 校验、服务端角色与 CORS 控制；定位空云端快照覆盖本地数据的问题后，将 AI 流程重构为请求级内存与字段级 delta，完成线上 DeepSeek、支持工单闭环和家长核心流程验收，同时配置 Node 20 / 22 GitHub Actions。"],
        },
        tags: ["TypeScript", "React 19", "Express", "oRPC", "Zod", "TanStack Query", "Zustand", "CloudBase", "Vitest", "MSW", "Playwright", "MCP", "GitHub Actions"],
        link: "查看源码",
      },
      {
        id: "nextgen",
        title: "CitiDirect NextGen",
        role: "Tech Lead / Senior Software Engineer · 2023—2025",
        body: "面向覆盖 96 个国家的企业网银平台，在新旧系统并行和严格安全合规约束下推进用户与权限管理现代化；担任中国团队 People Manager，带领 10 余人的中国—印度敏捷团队，并与另外 5 个跨国团队协作交付。",
        result: "正式接管用户与权限管理核心模块，在迁移期保持关键流程高可用，将核心模块自动化测试覆盖率稳定在 90% 以上，并获得 2024 年 Citi Gratitude Golden 奖项。",
        detail: {
          challenge: "CitiDirect 服务覆盖 96 个国家，日均处理约 4 万亿美元交易。权限平台改造期间，新旧系统需要长期并行，任何授权或审批数据偏差都可能影响企业客户，因此安全合规、数据一致性和服务连续性必须同时满足。",
          ownership: "作为 Tech Lead / Senior Software Engineer 和中国团队的 People Manager，我负责用户与权限管理模块的方案与交付，并带领由中国和印度成员组成的 10 余人敏捷团队。同时，我与分布在美国、印度、加拿大和智利的另外 5 个产品及研发团队协作，推进分阶段迁移。",
          approach: ["与产品、安全和运营团队梳理客户接入、用户授权、审批控制和访问规则，先沉淀为 API 契约、数据模型与迁移方案，再拆解为可交付的工程任务。", "Hands-on 设计并实现 React / Webpack Module Federation 宿主、共享依赖和核心权限界面，解除代码与发布耦合，让参与团队能够独立开发、测试和部署。", "交付集成 OIDC、OAuth 2.0 与 JWT 的 REST API，并构建 Kafka / MongoDB 双轨同步层；结合接口、日志与数据校验排查异常，保障迁移期权限和审批数据一致。", "将 BDD / Cucumber 纳入 CI/CD，使用 Docker 容器化并部署至 Kubernetes / OpenShift，同时围绕关键授权路径建立回归套件、发布检查和运维指引。"],
        },
        tags: ["React", "Module Federation", "REST API", "OIDC", "OAuth 2.0", "JWT", "Kafka", "MongoDB", "Docker", "Kubernetes / OpenShift"],
      },
      {
        id: "velocity",
        title: "Citi Velocity Search",
        role: "核心前端工程师 / Scrum Team Lead · 2017—2023",
        body: "重构服务近 10 万名机构用户的高流量搜索入口。设计元数据驱动渲染以承载异构金融内容，并通过 FDC3 集成独立交易体验。",
        result: "首屏加载与白屏时间缩短约 60%，交付 4 个核心生产模块，并凭借前端架构与性能工程贡献获得 2019 年 Citi Gratitude Golden 奖项。",
        detail: {
          challenge: "Citi Velocity Search 是平台第二大流量入口，服务近 10 万名机构投资者。重构既要接入研究报告、市场数据等异构金融内容，又要与独立交易面板协同，同时解决旧架构在高并发场景下的渲染延迟。",
          ownership: "我担任核心前端工程师与 Scrum Team Lead，主导前端重构，负责 UI 架构、性能方案以及 4 个生产模块的交付。",
          approach: ["使用 React、TypeScript、策略模式和元数据驱动渲染解耦不同内容组件，降低新增金融数据类型的前端接入成本。", "在微前端架构下通过 FDC3 统一跨应用 API，使搜索模块能够与独立交易面板互操作并实时同步状态。", "结合 Webpack Code Splitting、按需加载、Skeleton Screen 和多版本灰度发布，在避免一次性切换风险的同时缩短旧架构的白屏时间。"],
        },
        tags: ["React", "TypeScript", "Strategy Pattern", "FDC3", "Webpack", "Code Splitting", "Canary Release"],
      },
      {
        id: "platform",
        title: "React 平台与开发者生产力",
        role: "核心开发 · 2018—2025",
        body: "为分布式团队建设可复用 React / TypeScript 基础设施和工程规范，将重复的界面与发布工作沉淀为共享资产。",
        result: "形成支持 4 套设计系统、8 种主题和 3 条核心业务线的共享组件与交付基础，减少分布式团队在界面和发布环节的重复建设。",
        detail: {
          challenge: "多个分布式团队需要维护不同的视觉体系，却反复实现相同的组件行为、主题机制、文档和发布配置，不仅增加维护成本，也让产品体验和工程流程难以保持一致。",
          ownership: "作为核心开发，我参与从 0 到 1 建设 React / TypeScript 组件库，并负责部分扩展机制、工程规范、共享交付模板和使用文档。",
          approach: ["围绕共同行为设计组件 API，将业务线差异收敛到主题和配置层。", "使用 React、TypeScript 与 SCSS 支持 4 套设计系统和 8 种主题，同时保持核心实现统一。", "将组件资产与共享 CI/CD 模板、代码规范、API 文档和开发手册配套交付，帮助分布式团队统一代码审查、环境配置与独立发布方式。"],
        },
        tags: ["React", "TypeScript", "SCSS", "Design Systems", "Component APIs", "CI/CD", "Developer Documentation"],
      },
    ],
    galleryTabs: ["微信小程序", "支持工单", "安全规则"],
    galleryCaptions: ["微信开发者工具中的真实家庭端首页。", "基于结构化诊断证据、隐私最小化的支持队列。", "带可追溯决策依据的确定性发布前规则验证。"],
    galleryAlt: ["辅食搭子微信小程序首页", "辅食搭子家庭支持工单控制台", "辅食搭子安全规则验证控制台"],
    perspectiveTitle: "从三个视角了解系统",
    perspectives: [
      ["家庭端", "规划菜单、记录排敏，并在不离开产品的情况下上报问题。"],
      ["运营端", "处理经过授权、只包含元数据的工单，但无权修改家庭健康档案。"],
      ["工程端", "复用类型契约、确定性规则、测试，以及 MCP / Skill 工作流。"],
    ],
    evidence: [["300+", "用户 · 2026 年 8 月"], ["96.63%", "API 行覆盖率"], ["89.88%", "React 行覆盖率"]],
    journeyTitle: "成长路径",
    journeyIntro: "从前端系统工程到平台技术领导，再到独立产品实践，职责不断扩展，但主线始终是让复杂系统更容易理解、交付和复用。",
    journey: [
      { period: "2026—至今", title: "独立全栈产品实践", body: "独立构建并运营辅食搭子，覆盖产品设计、TypeScript 全栈工程、AI 工作流与云端交付。", stages: [] },
      { period: "2017—至今", title: "花旗 · 高级软件工程师 / Tech Lead", body: "在全球机构级平台中，从核心前端工程逐步拓展到全栈交付与技术领导。", stages: [
        ["近期阶段", "平台技术领导", "安全权限、API 契约、迁移架构、质量策略与跨国交付。"],
        ["早期阶段", "前端系统工程", "React 架构、机构搜索、微前端、FDC3 集成与性能工程。"],
      ] },
      { period: "2013—2017", title: "软件工程基础", body: "厦门大学软件工程与经济学双学位。", stages: [] },
    ],
    contactTitle: "一起构建经得起长期使用的软件。",
    contactBody: "我希望寻找同时重视产品判断、实现质量和长期所有权的全栈工程岗位。",
    email: "发送邮件",
    source: "GitHub 主页",
    archive: "早期技术写作 · 2016—2018",
    footer: "史学佳设计与开发",
  },
} as const;
